# Site settings
author: Holden Altaffer
title: home_break
header-img: img/home-bg.png
email: haltaffer@gmail.com
copyright_name: Holden Altaffer
description: > # this means to ignore newlines until "baseurl:"
  Kinda proud of it
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Cl3arglass

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
